// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.Globalization;
using System.Resources;

namespace TextToTalk.Resources;

[GeneratedCode("TextToTalk", "1.0")]
internal static class Strings
{
    private static readonly ResourceManager resourceManager =
        new("TextToTalk.Resources.Strings", typeof(Strings).Assembly);

    private static CultureInfo? culture;

    internal static ResourceManager ResourceManager => resourceManager;

    internal static CultureInfo? Culture
    {
        get => culture;
        set => culture = value;
    }

    internal static string ConfigurationTitle => Get(nameof(ConfigurationTitle));
    internal static string EnabledSuffix => Get(nameof(EnabledSuffix));
    internal static string DisabledSuffix => Get(nameof(DisabledSuffix));
    internal static string TabSynthesizerSettings => Get(nameof(TabSynthesizerSettings));
    internal static string TabPlayerVoices => Get(nameof(TabPlayerVoices));
    internal static string TabNpcVoices => Get(nameof(TabNpcVoices));
    internal static string TabChannelSettings => Get(nameof(TabChannelSettings));
    internal static string TabTriggersExclusions => Get(nameof(TabTriggersExclusions));
    internal static string SectionKeybinds => Get(nameof(SectionKeybinds));
    internal static string EnableKeybind => Get(nameof(EnableKeybind));
    internal static string TtsToggleKeybind => Get(nameof(TtsToggleKeybind));
    internal static string SectionGeneral => Get(nameof(SectionGeneral));
    internal static string AudioOutputDevice => Get(nameof(AudioOutputDevice));
    internal static string Volume => Get(nameof(Volume));
    internal static string VolumeHelp => Get(nameof(VolumeHelp));
    internal static string ReadNpcDialogueFromDialogueWindow => Get(nameof(ReadNpcDialogueFromDialogueWindow));
    internal static string CancelSpeechOnTextAdvance => Get(nameof(CancelSpeechOnTextAdvance));
    internal static string SkipVoicedNpcDialogue => Get(nameof(SkipVoicedNpcDialogue));
    internal static string ReadNpcDialogueFromBattleWindow => Get(nameof(ReadNpcDialogueFromBattleWindow));
    internal static string SkipMessagesFromYou => Get(nameof(SkipMessagesFromYou));
    internal static string OnlyMessagesFromYou => Get(nameof(OnlyMessagesFromYou));
    internal static string EnableNameWithSay => Get(nameof(EnableNameWithSay));
    internal static string NameNpcWithSay => Get(nameof(NameNpcWithSay));
    internal static string SayPlayerWorldName => Get(nameof(SayPlayerWorldName));
    internal static string DisallowMultipleSay => Get(nameof(DisallowMultipleSay));
    internal static string SayPartialName => Get(nameof(SayPartialName));
    internal static string OnlySayForename => Get(nameof(OnlySayForename));
    internal static string OnlySaySurname => Get(nameof(OnlySaySurname));
    internal static string LimitPlayerTtsFrequency => Get(nameof(LimitPlayerTtsFrequency));
    internal static string MessagesPerSecondFormat => Get(nameof(MessagesPerSecondFormat));
    internal static string SectionVoices => Get(nameof(SectionVoices));
    internal static string VoiceBackend => Get(nameof(VoiceBackend));
    internal static string SectionExperimental => Get(nameof(SectionExperimental));
    internal static string RemoveStutter => Get(nameof(RemoveStutter));
    internal static string RemoveStutterHelp => Get(nameof(RemoveStutterHelp));
    internal static string PlayerVoicesHint => Get(nameof(PlayerVoicesHint));
    internal static string UsePlayerVoicePresets => Get(nameof(UsePlayerVoicePresets));
    internal static string TableName => Get(nameof(TableName));
    internal static string TableWorld => Get(nameof(TableWorld));
    internal static string TablePreset => Get(nameof(TablePreset));
    internal static string ActionDelete => Get(nameof(ActionDelete));
    internal static string PlayerName => Get(nameof(PlayerName));
    internal static string PlayerWorld => Get(nameof(PlayerWorld));
    internal static string ActionAddPlayer => Get(nameof(ActionAddPlayer));
    internal static string PlayerAddFailedDuplicate => Get(nameof(PlayerAddFailedDuplicate));
    internal static string NpcVoicesHint => Get(nameof(NpcVoicesHint));
    internal static string UseNpcVoicePresets => Get(nameof(UseNpcVoicePresets));
    internal static string NpcName => Get(nameof(NpcName));
    internal static string ActionAddNpc => Get(nameof(ActionAddNpc));
    internal static string NpcAddFailedDuplicate => Get(nameof(NpcAddFailedDuplicate));
    internal static string ChannelPreset => Get(nameof(ChannelPreset));
    internal static string ActionNewPreset => Get(nameof(ActionNewPreset));
    internal static string ActionEdit => Get(nameof(ActionEdit));
    internal static string RecommendedForTriggerUse => Get(nameof(RecommendedForTriggerUse));
    internal static string EnableAllIncludingUndocumented => Get(nameof(EnableAllIncludingUndocumented));
    internal static string ChatTypeDebug => Get(nameof(ChatTypeDebug));
    internal static string ChatTypeCrossParty => Get(nameof(ChatTypeCrossParty));
    internal static string ChatTypeEnemyDefeatedByYou => Get(nameof(ChatTypeEnemyDefeatedByYou));
    internal static string ChatTypeOrchestrion => Get(nameof(ChatTypeOrchestrion));
    internal static string ChatTypeTellIncoming => Get(nameof(ChatTypeTellIncoming));
    internal static string ChatTypeTellOutgoing => Get(nameof(ChatTypeTellOutgoing));
    internal static string EnableAllChatTypesIncludingUndocumented => Get(nameof(EnableAllChatTypesIncludingUndocumented));
    internal static string TriggersHeading => Get(nameof(TriggersHeading));
    internal static string ExclusionsHeading => Get(nameof(ExclusionsHeading));
    internal static string TriggerInputHintFormat => Get(nameof(TriggerInputHintFormat));
    internal static string TriggersRegex => Get(nameof(TriggersRegex));
    internal static string ActionRemove => Get(nameof(ActionRemove));
    internal static string ActionAddFormat => Get(nameof(ActionAddFormat));

    internal static string Get(string key) => resourceManager.GetString(key, culture) ?? $"[{key}]";
}
